# Generated by Django 6.0.2 on 2026-03-02 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('viewed_by', models.ManyToManyField(blank=True, related_name='film2_viewers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
